### ISSUE TITLE
Gathering up beginner resources

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/unitary.fund#160]
If I want to create a page listing all the resources for quantum computing and information, would it be preferred to have it as a blogpost or create a separate page/tab on the unitary fund website ?

I am aware there are webpages that already do this but I feel they don't list the reasons as to why that resource was important to be listed for beginners. I am thinking of separating the discussion as hamiltonian simulation model, quantum circuit model, quantum algortihms, quantum error correction, quantum information and so on (textbook + papers).

**Comment by willzeng** [comment]
That would be a great blog post!

**Comment by willzeng** [comment]
Closed for now
