### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/unitary.fund#225]
Google's Lighthouse tool (available in chrome devtools) can perform automated accessibility (a11y) testing. It found two problems with our [`index.html`](https://github.com/unitaryfund/unitary-fund/blob/b7edb19675618544cf7fad852602f71ea1bc9544/index.html):
| problem | image |
| --- | --- |
| "Background and foreground colors do not have a sufficient contrast ratio" in the newsletter signup button | <img width="474" alt="Screen Shot 2022-05-23 at 11 10 47 AM" src="https://user-images.githubusercontent.com/12703123/169881075-35e5a5b4-641b-4a5f-bd7a-693a6b529240.png"> |
| "Links do not have a discernible name" for the icons we use for socials (in both the navigation menu and footer) | <img width="119" alt="Screen Shot 2022-05-23 at 11 11 54 AM" src="https://user-images.githubusercontent.com/12703123/169881217-46407294-f247-4ceb-abe7-4bb412d68e52.png"> |

Lighthouse also suggests the following ten things to manually check:
- The page has a logical tab order
- Interactive controls are keyboard focusable
- Interactive elements indicate their purpose and state
- The user's focus is directed to new content added to the page
- User focus is not accidentally trapped in a region
- Custom controls have associated labels
- Custom controls have ARIA roles
- Visual order on the page follows DOM order
- Offscreen content is hidden from assistive technology
- HTML5 landmark elements are used to improve navigation

Fixing the two main errors should be straightforward, but will need to be fixed on many pages since code is duplicated across many files. These kind of problems is presumably why @crazy4pi314 started porting the site to 11ty.[^1]

Some of these require a decent understanding of a11y and the ability to use a screen reader. cc @WrathfulSpatula since you may know of other a11y things to check for/improve.

I think this is an important issue as UF's mission is to create an ecosystem that benefits the _most_ people.

[^1]: Is this something we'd still like to do?

**Comment by crazy4pi314** [comment]
1000% agree this is pretty critical, and was exactly why I ported the site to 11ty. With the exception of a few of the more recent posts, that new backend addresses most of the user/contributor accessibility issues, and thanks for surfacing the a11y and lighthouse issues that should be even higher priority.

**Comment by WrathfulSpatula** [comment]
Since I was CCed, I'll just say that 11ty sounds like a good idea to me, too, but I don't have anything to add off the top of my head. But, I'm following the issue ticket, and feel free to ask for my help in implementation, if you'd like.

**Comment by natestemen** [comment]
With the redesign, it looks like there is only thing that lighthouse has flagged:

<img width="711" alt="Screenshot 2023-08-10 at 11 26 23 AM" src="https://github.com/unitaryfund/unitary.fund/assets/12703123/9ef9e98b-568f-4701-825d-fe1f280710d7">



> ### Links do not have a discernible name
> Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users. [Learn more](https://web.dev/link-name/?utm_source=lighthouse&utm_medium=devtools).


cc @joshdavenport

**Comment by joshdavenport** [comment]
Ah, good spot. On it

**Comment by joshdavenport** [comment]
Should be better now. As an aside to accessibility but related to Lighthouse/PageSpeed Insights, the performance item around short cache times is something you can't change via GitHub pages but you could adjust by putting Cloudflare in front of pages.

**Comment by natestemen** [comment]
Thanks Josh! Could you clarify, as an end user, how would using cloudflare improve the experience? Faster load times?


I'm going to close this issue for now since it seems the most problematic a11y issues are complete!
