### ISSUE TITLE
Automation to automatically convert md blog to html

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#276]
Automation to automatically convert the .md file to a blog to .html.
This allows contributors to avoid running the pandoc script themselves.
https://github.com/unitaryfund/unitary-fund#writing-a-blog-post

This could automate also updating the index.

This could also provide an automatically generated temp website in the PR, similarly to what done by readthedocs for Mitiq, to check the look of the blog post.

**Comment by andre-a-alves** [comment]
Has the idea of a static generator been considered? I've set up a couple sites with Eleventy, and converting this site to use that would not be difficult at all. It allows for seeing your blog post (or any changes for that matter) served locally as you work, can take care of the indexing automatically, is compatible with GitHub Actions, and to see a site before merging, all you'd have to do is clone the branch and run `npm run serve`. The current format and style does not have to be changed at all to do it, either. 

Let me know if there is interest.

**Comment by natestemen** [comment]
With the redesign/rebuild this should be taken care of :)
