### ISSUE TITLE
Add bibliographic information to publications

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#343]
Add bibliographic information to publications on the research page, also for the UF team research, like what is already done for the microgrants' research [publications](https://unitary.fund/research/publications/).

**Comment by nathanshammah** [comment]
@vprusso can I ask your help on this?

**Comment by vprusso** [comment]
Addressed in https://github.com/unitaryfund/unitary.fund/pull/362 @nathanshammah
