### ISSUE TITLE
Tidy up tags in microgrants

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#347]
Tidy up tags in microgrants. I propose to use a set of general tags + some specific tags. 

# part 1: Remove / consolidate tags
Remove some tags, like `quantum` (too generic) or `quantum cnn` (too specific) and consolidate others, like `quantum algorithm` and `quantum algorithms`.

# part 2: Add tags
Examples of general tags (existing already on airtable):
- `software`
- `education`
- `community`
- `research`

Additional proposed tags:
- `publication` (if a publication is associated to the grant)
- programming language. For example, `python`

Specific tags:
- in some cases, allow for specific tags, that could be found elsewhere like `compiler`, `qworld` etc.

**Comment by KallieFerguson** [comment]
As discussed, we may also want to add tags for "Qiskit" or perhaps other platforms.

**Comment by KallieFerguson** [comment]
Here are our current tags and I added a strikethrough for my suggestions to get rid of (I suspect we can pare down even more though)

1.	Benchmark
2.	C
3.	C++
4.	Classical Algorithms
5.	Cold Atoms
6.	Compiler
7.	Computer Science
8.	Error Mitigation 
9.	~~Experiments~~ - Seems to vague to be super useful as a tag 
10.	Fermion
11.	Finance
12.	Games
13.	~~Ganes~~ – Used only once for Toqito and I suspect is meant to be “games”
14.	GPU
15.	Gradient Descent
16.	Hamiltonian
17.	Haskell
18.	~~Intern~~
19.	Javascript
20.	Julia
21.	Krylov
22.	Machine Learning
23.	Medical – Unsure about this one, if we keep maybe we should add tags for other application areas, like chemistry?
24.	Metriq
25.	~~Microsoft~~
26.	MPS
27.	Non-Profit
28.	Open Hardware
29.	Openqasm
30.	Optimization
31.	~~Optmization~~ – Misspelling of optimization
32.	Physics
33.	Podcast – Maybe this should be something different, such as “communication”?
34.	Probability
35.	Python
36.	Q#
37.	QAOA
38.	QEC
39.	QIR
40.	Qiskit
41.	QML
42.	Quantum
43.	~~Quantum Algorithm~~
44.	Quantum Algorithms 
45.	Quantum CNN
46.	Quantum Computing
47.	Quantum Education
48.	Quantum Error Correction – Keep either this one or QEC, not both
49.	Quantum Language
50.	~~Quantum Optimization~~ – Keep Optimization and remove “quantum”
51.	Quantum Systems
52.	Rust
53.	Scala
54.	Simulation
55.	~~Simulator~~ - Keep Simulation above
56.	Software
57.	Tensor Network
58.	Tex - What is this one?
59.	Visualization
60.	~~Visualizations~~
61.	VQA
62.	VQE

**Potential added tags:** 
1. Mitiq
2. Pennylane
3. Cirq
4. TKET
5. Braket

@nathanshammah
