### ISSUE TITLE
Events page not displaying all events

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/unitary.fund#357]
I'm seeing 2 problems with the events page (https://unitary.fund/community/events/)

1. The mitiq community call is not displayed
2. the metriq jam session is being duplicated many times

<details>
<summary>screenshot</summary>
<img width="1024" alt="Screenshot 2023-08-23 at 10 34 03 AM" src="https://github.com/unitaryfund/unitary.fund/assets/12703123/a0cdc562-1134-4402-8004-5521c2dce9d6">
</details>

**Comment by nathanshammah** [comment]
Seems almost 100% ok (1 duplication, ending from Wed 11 Oct). Not sure what's the reason.

**Comment by natestemen** [comment]
Nov 24th also has a duplicate metriq jam session, but looks like none thereafter (at least until April '24). Glad this is sorting itself out even if we don't know why!
