### ISSUE TITLE
2023 QOSS survey page does not mention the survey is closed, but should

### ISSUE THREAD

**Issue by mhucka** [unitaryfund/unitary.fund#455]
The page at https://unitary.fund/posts/2023_qoss_survey/ implies the survey is still open. It should probably be changed to say that the survey has concluded.

(Of course, the year should be a tip-off, but it would be nice if the page would instead say that the survey is now closed, so that curious people like me don't waste time clicking the link :-).)

**Comment by nathanshammah** [comment]
Thanks for the feedback, addressed now in #463.
