### ISSUE TITLE
Update UF staff

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#464]
Add new members of staff to homepage ([here](https://github.com/unitaryfund/unitary.fund/blob/main/src/content/team/main.json)), @jordandsullivan @cosenal, with their preferred links.

**Comment by jordandsullivan** [comment]
Added myself.

**Comment by cosenal** [comment]
@nathanshammah I wanted to push the change, but it looks like I am not a maintainer of the [unitaryfund/all](https://github.com/orgs/unitaryfund/teams/all) team on Github, so I don't have write permissions on this repo 🤔 I could fork, but I may as well wait for permissions.

**Comment by cosenal** [comment]
@nathanshammah still not working. I am not admin of this repository, so I can't see how the permissions are set.

**Comment by nathanshammah** [comment]
Added you both now to engineering, but only a few folks are added directly to this repo, so I don't think that's the issue. @WrathfulSpatula @beecastanon can you help look into this? (as a temporary fix for this issue only it could work to fork and open a PR.)
