### ISSUE TITLE
Update stats on microgrant page

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#492]
On the microgrant page, https://unitary.fund/grants/, we still mention

"We’ve awarded microgrants to over 89 teams across 26 countries, resulting in 18+ completed or planned publications, welcoming 13 people into the field, and helping to form 2 new startups and 1 new non-profit."

The page to update, in markdown, is this in the source code: https://github.com/unitaryfund/unitary.fund/blob/main/src/pages/grants.mdx

We are now at 100+ grants. Let's update all figures that have grown and keep this blurb up to date in general.

**Comment by KallieFerguson** [comment]
@nathanshammah https://github.com/unitaryfund/unitary.fund/pull/498

**Comment by willzeng** [comment]
Closed by #498
